batch_size = 64
stack_size = 1
num_epochs = 20
precision = "f32"
debug_mode = false
do_profile = false
display = "progress"

[data]
dataset_name = "mp2022"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 30
test_split = 3
valid_split = 3
batches_per_group = 0

[log]
logs_per_epoch = 16
epochs_per_ckpt = 5
epochs_per_valid = 0.5

[train]
base_lr = 1.0
max_grad_norm = 3.0
ema_gamma = 0.99
steps_between_ema = 16

[model]
residual = false
resid_init = "zeros"
outs_per_node = 128
block_reduction = "last"
share_species_embed = true
hidden_irreps = [
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
    "128x0e + 64x1e + 32x2e",
]

[train.loss]
energy_weight = 1
force_weight = 0
stress_weight = 0

[train.lr_schedule]
kind = "polynomial"
warmup_frac = 0.1
start_lr = 0.01
end_lr = 0.01
power = 1.0

[train.optimizer]
base_lr = 1.0
kind = "prodigy"
weight_decay = 0.001
beta_1 = 0.9
beta_2 = 0.999

[model.node_embed]
embed_dim = 128
kind = "linear"

[model.edge_embed]
r_max = 5.0
r_max_trainable = false
radius_transform = "Identity"

[model.interaction]
kind = "simple"
residual = true
linear_intro = true
linear_outro = true

[model.readout]
kind = "identity"

[model.self_connection]
kind = "gate"

[model.rescale]
kind = "sevennet"

[model.head]
inner_dims = [64]
activation = "Identity"
final_activation = "Identity"
out_dim = 0
dropout = 0.0
residual = false
num_heads = 1
use_bias = false
normalization = "Identity"

[train.loss.reg_loss]
loss_delta = 0.015625
use_rmse = false

[model.edge_embed.radial_basis]
num_basis = 8
kind = "bessel"
freq_trainable = true
use_sinc = true

[model.edge_embed.envelope]
kind = "xplor"
cutoff_start = 0.9

[model.interaction.message]
kind = "sevennet-conv"
max_ell = 2

[model.interaction.message.radial_weight]
inner_dims = [64, 64]
activation = "normalized_silu"
final_activation = "Identity"
out_dim = 0
dropout = 0.0
residual = false
num_heads = 1
use_bias = false
normalization = "Identity"
